### ISSUE TITLE
Pass arguments to encoder

### ISSUE THREAD

**Issue by jimbow973** [alexheretic/ab-av1#106]
Hi, 
Thank you for the ab-av1 project, just discovered it yesterday, very helpful to squeeze videos. 
My concern is how to pass arguments to the encoder like "enable-qm=1" or "tune=screen" whether it is with SVT or libsvtav1 or libaom
`ab-av1 auto-encode -e libsvtav1 -i test1.mp4 --enc-input enable-qm=1 --min-vmaf 95 --max-crf 63 --preset 4` is not working
or
`ab-av1 auto-encode -e libaom-av1 --min-vmaf 95 --max-crf 63 --acodec libopus --enc b:a=64k --aom-params enable-qm=1 --preset 8 -i test1.mp4 ` is not working too.
Thanks,
Jim

**Comment by alexheretic** [comment]
`--enc  VAL` & `--enc-input VAL` are for providing ffmpeg args.

`--enc aom-params=foo=bar:baz=qux` will become `ffmpeg ... -aom-params foo=bar:baz=qux`

For svt-av1 you can use `--svt VAL` which is a bit nicer as you can use it multiple times.

It's possible to open your system task manager/process viewer and look at what ffmpeg args are being used during an encode run.

Can we improve the help output for these options?

**Comment by jimbow973** [comment]
Amazing, thank you Alex. I spent a good time trying to figure how to pass the arguments, just found some hints in your blog post. So yes, it would be fine to include it in the help output `--help`.

Can it work with 2 passes ffmpeg encoding too? the CRF value isn't required for libaom-av1 first pass, so I would use ffmpeg for the 1st pass then ab-av1 to launch the 2nd pass using `auto-encode`? possible?

**Comment by alexheretic** [comment]
I've never looked into 2 pass support so i don't think this would work, or
not very well.

The app is currently focused on single pass crf runs. Perhaps more can be
done with 2 pass.

**Comment by iPaulis** [comment]
I would be interested in trying 2 pass too.
I tried passing --svt arguments like `--passes 2 --stats stat_file.stat` in a single command line, it runs, but it has no effect in the results.

**Comment by jimbow973** [comment]
yeah, 2 pass with either libaom-av1 and libsvtav1. 
Also, ffmpeg is still buggy regarding some of libaom switches (like fp-mt=1 or enable-fwd-kf =1) - I don't use SVT, quality is way lower than aomenc for screen recording despite using scm=1. My suggestion would be to use aomenc.exe directly like in av1an instead of relying only on libaom.

**Comment by iPaulis** [comment]
It seems that 2 pass is supported in standalone svtav1enc but not in ffmpeg libsvtav1 according to [this](https://gist.github.com/mrintrepide/b3009f5d0f08d437ebbb4c17cbf36e18) and [this](https://streaminglearningcenter.com/encoding/svt-av1-vs-libaom.html).
So the svtav1 implementation is not complete in ffmpeg yet.

**Comment by alexheretic** [comment]
In the restrictive limits of my knowledge I don't think 2-pass is a good fit for this tool. If anyone can explain a good motivation for 2-pass here please raise an issue for it, otherwise I think this issue can be closed.
