### ISSUE TITLE
Can't get "ab-av1 auto-encode" to encode with 10-Bit Color Depth with *_vaapi-Encoders

### ISSUE THREAD

**Issue by Gnatzelle** [alexheretic/ab-av1#297]
This might be a really dumb question to a really simple solution, but as the title says i'm unable to get a 10-Bit Video-Encode out of ab-av1 with the auto-encode mode.

Running `ab-av1 auto-encode -e av1_vaapi --pix-format yuv420p10le --enc compression_level=1 --thorough -i ...` works fine, but the output is still only 8-Bit.

Adding a --vfilter option like `'format=nv12,hwupload'` throws this ffmpeg-Error:
`Incompatible pixel format 'yuv420p10le' for codec 'av1_vaapi', auto-selecting format 'vaapi'`

vainfo -a shows that H264, H265 and AV1 are all supporting 10-Bit Encoding
(VA_RT_FORMAT_YUV420_10 / VA_RT_FORMAT_YUV420_10BPP)

Manually running ffmpeg with either
`ffmpeg -vaapi_device /dev/dri/renderD128 -i input.mkv -vf 'format=p010,hwupload' -c:v av1_vaapi -b:v 15M output.mkv`
or
`ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i input.mkv -vf 'scale_vaapi=format=p010' -c:v av1_vaapi -b:v 15M output.mkv`

as the wiki says, produce the wanted 10-Bit Files...

**Comment by mr44er** [comment]
I think yuv420p is hardcoded for the moment.



> Running `ab-av1 auto-encode -e av1_vaapi --pix-format yuv420p10le --enc compression_level=1 --thorough -i ...` works fine, but the output is still only 8-Bit.

Can you try:
`ab-av1 auto-encode -e av1_vaapi --vfilter "format=p010,hwupload" --pix-format yuv420p10le --enc compression_level=1 --thorough -i ...`

**Comment by alexheretic** [comment]
Thanks for the report. Currently ab-av1 always sets an ffmpeg pixel format. This is useful for svt-av1 but is causing this issue. I think the solution is to simply not specify it outside of particular vcodecs and let ffmpeg use its own defaults then.

**Comment by alexheretic** [comment]
I've merged #298 which will remove the behaviour of always setting pixel format _(except for libsvtav1, libaom-av1 & librav1e)_.

This should mean you get the same behaviour as manual ffmpeg.

**Comment by Gnatzelle** [comment]
I'm really thankful for getting into this...but still no Luck, or i am really too stupid -.-"

Now i'm getting
_`Impossible to convert between the formats supported by the filter 'Parsed_format_3' and the filter 'auto_scale_1'`_

when i try

`ab-av1 auto-encode -e av1_vaapi --enc-input hwaccel_device=/dev/dri/renderD128 --vfilter scale_vaapi=format=p010 --enc compression_level=21 --thorough -i ...`

or

_`Impossible to convert between the formats supported by the filter 'graph -1 input from stream 0:0' and the filter 'auto_scale_0'`_

when

`ab-av1 auto-encode -e av1_vaapi --enc-input vaapi_device=/dev/dri/renderD128 --vfilter "format=p010,hwupload" --enc compression_level=21 --thorough -i ...`
